### PR TITLE
Add lib_teleport

### PR DESCRIPTION
**Pull request by Akarys42**
This library allows the datapack to teleport a player to arbitrary coordinates stored in scoreboards.

This would allow us to make a `/home` command.

### CODE REVIEW

**Comment by aphkyle** [comment]
Should we put commands in the meta folder or should we not? I mean, we probably will have more pulls about commands later, or will it be too messy?

**Comment by Akarys42** [comment]
> Should we put commands in the meta folder or should we not? I mean, we probably will have more pulls about commands later, or will it be too messy?

What commands are you taking about? The constants inside the generator?

**Comment by aphkyle** [comment]
> > Should we put commands in the meta folder or should we not? I mean, we probably will have more pulls about commands later, or will it be too messy?
> 
> What commands are you talking about? The constants inside the generator?

yes, those

**Comment by Akarys42** [comment]
If we can come up with a decent system when loading commands, sure, but I'm afraid things would get more spaghetti-like if we start fetching commands from files

**Review by gustavwilliam — APPROVED** [review]
Looks good to me.

However, I don't feel qualified to review the functionality of this. If you think this works now, merge it and we can do the final testing in production basically.

**Pull request merged**
